name: Collect Stats
on:
  workflow_dispatch: { }
  schedule:
    # Runs every 30 minutes from 6 to 22 Tue-Sun (Opening Times)
    - cron: "*/30 6-22 * * 0,2-6"
      timezone: "Europe/Berlin"

jobs:
  collectStats:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: collect stats
        run: ./get-info.sh

      - name: extract stats
        run: ./extract-stats.sh

      - name: delete stats.json
        run: rm -f stats.json

      - name: push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add stats.csv
            git commit -m "Update stats.csv [$(date -u '+%Y-%m-%d %H:%M:%S UTC')]"
            git push
          else
            echo "nothing to push";
          fi
          

